@extends('layouts.page')

@section('content')
    <p>Ceci est le contenu de la page</p>
    <p>Ceci est le contenu de la page</p>
    <p>Ceci est le contenu de la page</p>
    <p>Ceci est le contenu de la page</p>
    <p>Ceci est le contenu de la page</p>
    <p>Ceci est le contenu de la page</p>
    <p>Ceci est le contenu de la page</p>
    <p>Ceci est le contenu de la page</p>
    <p>Ceci est le contenu de la page</p>
    <p>Ceci est le contenu de la page</p>
    <p>Ceci est le contenu de la page</p>
    <p>Ceci est le contenu de la page</p>
    <p>Ceci est le contenu de la page</p>
    <p>Ceci est le contenu de la page</p>
    <p>Ceci est le contenu de la page</p>
    <p>Ceci est le contenu de la page</p>
    <p>Ceci est le contenu de la page</p>
    <p>Ceci est le contenu de la page</p>
    <p>Ceci est le contenu de la page</p>
    <p>Ceci est le contenu de la page</p>
    <p>Ceci est le contenu de la page</p>
    <p>Ceci est le contenu de la page</p>
    <p>Ceci est le contenu de la page</p>
    <p>Ceci est le contenu de la page</p>
    <p>Ceci est le contenu de la page</p>
    <p>Ceci est le contenu de la page</p>
    <p>Ceci est le contenu de la page</p>
    <p>Ceci est le contenu de la page</p>
    <p>Ceci est le contenu de la page</p>
    <p>Ceci est le contenu de la page</p>
    <p>Ceci est le contenu de la page</p>
    <p>Ceci est le contenu de la page</p>
    <p>Ceci est le contenu de la page</p>
    <p>Ceci est le contenu de la page</p>
    <p>Ceci est le contenu de la page</p>
    <p>Ceci est le contenu de la page</p>
    <p>Ceci est le contenu de la page</p>
    <p>Ceci est le contenu de la page</p>
    <p>Ceci est le contenu de la page</p>
    <p>Ceci est le contenu de la page</p>
    <p>Ceci est le contenu de la page</p>
    <p>Ceci est le contenu de la page</p>
    <p>Ceci est le contenu de la page</p>
    <p>Ceci est le contenu de la page</p>
    <p>Ceci est le contenu de la page</p>
    <p>Ceci est le contenu de la page</p>
    <p>Ceci est le contenu de la page</p>
    <p>Ceci est le contenu de la page</p>
    <p>Ceci est le contenu de la page</p>
    <p>Ceci est le contenu de la page</p>
    <p>Ceci est le contenu de la page</p>
    <p>Ceci est le contenu de la page</p>
    <p>Ceci est le contenu de la page</p>
    <p>Ceci est le contenu de la page</p>
    <p>Ceci est le contenu de la page</p>
    <p>Ceci est le contenu de la page</p>
    <p>Ceci est le contenu de la page</p>
    <p>Ceci est le contenu de la page</p>
    <p>Ceci est le contenu de la page</p>
    <p>Ceci est le contenu de la page</p>
@stop
